### ISSUE TITLE
small correction to comments in selfhosted_sites.yml

### ISSUE THREAD

**Issue by james-cook** [ReinerNippes/selfhosted_on_docker#4]
Add the "**base.**" prefix to the **{{base_domain}}** to give: **base.{{ base_domain }}**

```
# adminer is a webfront end for your database at https://base.{{ base_domain }}/adminer
adminer_enabled: false

# portainer is a webfront end for docker host at https://base.{{ base_domain }}/portainer/
portainer_enabled: true

# user for traefik dashboard at https://base.{{ base_domain }}/traefik
traefik_api_enabled: false

```

**Comment by james-cook** [comment]
or... better still, make the "base" sub-domain customisable:
```
# Define your selfhosted sites here

base_domain: example.com
base_sub_domain: base1
.
.
# adminer is a webfront end for your database at https://{{base_sub_domain}}.{{ base_domain }}/adminer
adminer_enabled: false

# portainer is a webfront end for docker host at https://{{base_sub_domain}}.{{ base_domain }}/portainer/
portainer_enabled: true

# user for traefik dashboard at https://{{base_sub_domain}}.{{ base_domain }}/traefik
traefik_api_enabled: true


selfhosted_sites:
  - name: base
    type: base
    server_fqdn: {{base_sub_domain}}.{{ base_domain }}

```

More comfortable if you have several hosts... (in particular when testing:) )
